---
- name: SSH publikus kulcs szétterítése a célgépekre
  hosts: all
  gather_facts: false
  become: true  # Root jog szükséges a felhasználó kulcsának módosításához

  vars:
    ssh_user: "mcs"
    # Itt adjuk meg a tiszta szöveges jelszót
    ssh_password_raw: "root123"
    # Itt add meg a nyilvános kulcsot
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDhXnwfOYukkPIWtiqtfL4Hwdlb2rumq/6zQUqrqU32obNBX90ILOo8jx9I6xdCIs7N0uNKDRWR8ZTO6ve1H1j9V8JcXZse9zbZVSi1RpmQMAQg769o+dmhJuE9122sAQunR/IHkIO3bMaSCKZUxlP6hogG06x1SZhrEoY0fVSzPVNYe+bqKZj1wDr1G+wIQkGUKpkj1N0C8EbKrltIMozlYkh4wZOXiK/bvgcEUGRP2PUvQ53AHA9zwlaqysSsd5aMmJv+4MM3HOhhbIroUC4731G4mFJdqSlv4CrDDN5eixcjwiTcZXlqJ54IO7iQLusit6gF6Yma0TswJdO21/nTtXLEzD7IW5FisqGaV9Qr/0Z/UzEpvVZT1qPYxjHQ9rdfhKXu7sphwZ3lLp6iR7+I9kw/oB33V2ylnURzuGDTEopvMgZOtPvVFQZsaKx1/ZRC+NSR3kHk3bLX2dY+LtiNG1+xVPv8b06fzJZ4HIEFVtgmGJOiDSzNypxi8YTnCo8= mcs@://example.com"

  tasks:
    - name: Ellenőrizzük, hogy létezik-e az mcs felhasználó és dinamikusan hasheljük a jelszót
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        # A password_hash szűrő a háttérben biztonságos SHA-512 hasht készít egyedi salttal
        password: "{{ ssh_password_raw | password_hash('sha512') }}"
        state: present
        shell: /bin/bash

    - name: SSH kulcs hozzáadása az authorized_keys fájlhoz
      ansible.posix.authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ public_key }}"
